from datetime import datetime


def generate_report(repo_url, task_outputs):
    
    # Start composing the report
    report_sections = [f"# 🧠 GitHub Repo Audit Report\n\n**🔗 Repo URL:** {repo_url}\n\n---\n"]

    for task_output in task_outputs:
        section_title = task_output.name.replace("_", " ").title()
        section_content = task_output.raw.strip() if task_output.raw else "*No output*"
        report_sections.append(f"## 🔹 {section_title}\n\n{section_content}\n\n---\n")

    report_sections.append("*Generated by RepoAuditorCrew*")
    final_report = "\n".join(report_sections)

    # Save as Markdown
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    filename = f"repo_audit_report_{timestamp}.md"

    with open(filename, "w") as f:
        f.write(final_report)
    print(f"Report saved as {filename}")